services:
  - type: web
    name: nouravey
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn apps.core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: GEMINI_API_KEY
        sync: false
      - key: IQAIR_API_KEY
        sync: false
      - key: FIRMS_MAP_KEY
        sync: false
      - key: SUPABASE_S3_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_SECRET_KEY
        sync: false
      - key: SUPABASE_S3_BUCKET
        sync: false
      - key: SUPABASE_S3_ENDPOINT
        sync: false
