# Generated by Django 4.2.30 on 2026-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('satellite', '0001_initial'),
        ('reports', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_latitude', models.FloatField()),
                ('center_longitude', models.FloatField()),
                ('ward', models.CharField(blank=True, choices=[('port_reitz', 'Port Reitz'), ('kipevu', 'Kipevu'), ('airport', 'Airport'), ('changamwe', 'Changamwe'), ('chaani', 'Chaani'), ('jomvu_kuu', 'Jomvu Kuu'), ('miritini', 'Miritini'), ('mikindani', 'Mikindani'), ('mjambere', 'Mjambere'), ('junda', 'Junda'), ('bamburi', 'Bamburi'), ('mwakirunge', 'Mwakirunge'), ('mtopanga', 'Mtopanga'), ('magogoni', 'Magogoni'), ('shanzu', 'Shanzu'), ('frere_town', 'Frere Town'), ('ziwa_la_ngombe', "Ziwa la Ng'ombe"), ('mkomani', 'Mkomani'), ('kongowea', 'Kongowea'), ('kadzandani', 'Kadzandani'), ('mtongwe', 'Mtongwe'), ('shika_adabu', 'Shika Adabu'), ('bofu', 'Bofu'), ('likoni', 'Likoni'), ('timbwani', 'Timbwani'), ('mji_wa_kale', 'Mji wa Kale/Makadara'), ('tudor', 'Tudor'), ('tononoka', 'Tononoka'), ('majengo', 'Majengo'), ('shimanzi', 'Shimanzi/Ganjoni')], max_length=50)),
                ('subcounty', models.CharField(blank=True, choices=[('changamwe', 'Changamwe'), ('jomvu', 'Jomvu'), ('kisauni', 'Kisauni'), ('nyali', 'Nyali'), ('likoni', 'Likoni'), ('mvita', 'Mvita')], max_length=50)),
                ('score', models.FloatField(default=0)),
                ('severity_label', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('narrative', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reports', models.ManyToManyField(related_name='hotspots', to='reports.report')),
                ('satellite_hotspots', models.ManyToManyField(blank=True, related_name='hotspots', to='satellite.satellitehotspot')),
                ('sensor_readings', models.ManyToManyField(blank=True, related_name='hotspots', to='sensors.sensorreading')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
