# Generated by Django 5.2.16 on 2026-07-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='predicted_trend',
            field=models.CharField(blank=True, choices=[('worsening', 'Likely to Worsen'), ('stable', 'Likely to Remain Stable'), ('improving', 'Likely to Improve'), ('insufficient_data', 'Insufficient Data')], max_length=20),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='prediction_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='prediction_rationale',
            field=models.TextField(blank=True),
        ),
    ]
