# Generated by Django 4.2.30 on 2026-07-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(choices=[('port_reitz', 'Port Reitz'), ('kipevu', 'Kipevu'), ('airport', 'Airport'), ('changamwe', 'Changamwe'), ('chaani', 'Chaani'), ('jomvu_kuu', 'Jomvu Kuu'), ('miritini', 'Miritini'), ('mikindani', 'Mikindani'), ('mjambere', 'Mjambere'), ('junda', 'Junda'), ('bamburi', 'Bamburi'), ('mwakirunge', 'Mwakirunge'), ('mtopanga', 'Mtopanga'), ('magogoni', 'Magogoni'), ('shanzu', 'Shanzu'), ('frere_town', 'Frere Town'), ('ziwa_la_ngombe', "Ziwa la Ng'ombe"), ('mkomani', 'Mkomani'), ('kongowea', 'Kongowea'), ('kadzandani', 'Kadzandani'), ('mtongwe', 'Mtongwe'), ('shika_adabu', 'Shika Adabu'), ('bofu', 'Bofu'), ('likoni', 'Likoni'), ('timbwani', 'Timbwani'), ('mji_wa_kale', 'Mji wa Kale/Makadara'), ('tudor', 'Tudor'), ('tononoka', 'Tononoka'), ('majengo', 'Majengo'), ('shimanzi', 'Shimanzi/Ganjoni')], max_length=50)),
                ('subcounty', models.CharField(choices=[('changamwe', 'Changamwe'), ('jomvu', 'Jomvu'), ('kisauni', 'Kisauni'), ('nyali', 'Nyali'), ('likoni', 'Likoni'), ('mvita', 'Mvita')], editable=False, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.ImageField(upload_to='reports/photos/')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], max_length=10)),
                ('text_description', models.TextField(blank=True)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='reports/voice/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('pollution_type', models.CharField(choices=[('smoke', 'Smoke'), ('dust', 'Dust'), ('burning', 'Open Burning'), ('industrial', 'Industrial'), ('unknown', 'Unknown')], max_length=20)),
                ('severity', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('likely_cause', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='unresolved', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
